FROM greenblattryan/blender-render

RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/rgreenblatt/neural-render && cd neural-render

# TODO: render entrypoint of some kind?
